In [17]:
import pandas as pd
import numpy as np
from data_profiling import ProfileReport
# loading data:

data = pd.read_csv("../../data/housing_price_data_set.csv")


columns_list =  list(data.columns)
columns_list[1:]

['price',
 'lotsize',
 'bedrooms',
 'bathrms',
 'stories',
 'driveway',
 'recroom',
 'fullbase',
 'gashw',
 'airco',
 'garagepl',
 'prefarea']

In [18]:
data.head(5)

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,2,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,3,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,4,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,5,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [19]:
data = data.drop(columns=["Unnamed: 0"])
data

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     546 non-null    float64
 1   lotsize   546 non-null    int64
 2   bedrooms  546 non-null    int64
 3   bathrms   546 non-null    int64
 4   stories   546 non-null    int64
 5   driveway  546 non-null    object
 6   recroom   546 non-null    object
 7   fullbase  546 non-null    object
 8   gashw     546 non-null    object
 9   airco     546 non-null    object
 10  garagepl  546 non-null    int64
 11  prefarea  546 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 51.3+ KB

In [21]:
data.describe()

,price,lotsize,bedrooms,bathrms,stories,garagepl
count,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000
mean,68121.597070,5150.265568,2.965201,1.285714,1.807692,0.692308
std,26702.670926,2168.158725,0.737388,0.502158,0.868203,0.861307
min,25000.000000,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,49125.000000,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,62000.000000,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,82000.000000,6360.000000,3.000000,2.000000,2.000000,1.000000
max,190000.000000,16200.000000,6.000000,4.000000,4.000000,3.000000

In [23]:
#create an array: List → ndarray
nums = np.array([10,20,30,50])
nums

array([10, 20, 30, 50])

In [27]:
#Matrix of 0s.

matrix = np.zeros((3,4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
#Matrix of 1s.

matrix = np.ones((2,3))
matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
#Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
#Uninitialized array
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
#Fill with constants: np.full((m,n), value)
np.full((2,3), "A")

array([['A', 'A', 'A'],
       ['A', 'A', 'A']], dtype='<U1')

In [35]:
#Integer sequence: np.arange(start, stop, step)
np.arange(1,5,1)

array([1, 2, 3, 4])

In [39]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [ ]:
#Equal intervals: np.linspace(start, stop, num)

In [42]:
np.linspace(1,4,2)

array([1., 4.])

In [43]:
#Logarithmic spacing
np.logspace(1,3,1)

array([10.])

In [46]:
#Repeat:
np.repeat([2,3,6],3)

array([2, 2, 2, 3, 3, 3, 6, 6, 6])

In [49]:
np.tile([2,3,5],2)

array([2, 3, 5, 2, 3, 5])

In [51]:
## Array Properties:
data.shape

(546, 12)

In [52]:
# Total axes:
data.ndim

2

In [55]:
# Total elements:
data.size

6552

In [62]:
nums = [10,20,30,40]
nums_arr = np.array(nums)
nums_arr

array([10, 20, 30, 40])

In [63]:
nums_arr.dtype

dtype('int64')

In [64]:
#bytes per element:
nums_arr.itemsize

8

In [65]:
#Total memory:
nums_arr.nbytes

32

In [66]:
len(nums_arr)

4

In [70]:
#Indexing and Slicing:
nums_arr[1:5]

array([20, 30, 40])

In [72]:
nums_arr[::-1]

array([40, 30, 20, 10])

In [114]:
arr1 = np.array([[1,2,3],
                 [6,7,8]])

In [98]:
arr1

array([[1, 2, 3],
       [6, 7, 8]])

In [97]:
arr1.shape

(2, 3)

In [102]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 6],
       [7, 8]])

In [103]:
flat = arr1.flatten()
flat

array([1, 2, 3, 6, 7, 8])

In [109]:
flat[0] = 50
print(flat)
print(arr1)  # Original array didn't get modify

[50  2  3  6  7  8]
[[1 2 3]
 [6 7 8]]

In [110]:
# creates a view instead of copy
r = arr1.ravel()  
print(r)

[1 2 3 6 7 8]

In [112]:
r[0] = 100
print(r)
print(arr1)  # original array got modified

[100   2   3   6   7   8]
[[100   2   3]
 [  6   7   8]]

In [117]:
print(arr1)
print("transposed array:", arr1.transpose())

[[1 2 3]
 [6 7 8]]
transposed array: [[1 6]
 [2 7]
 [3 8]]

In [120]:
# T: same as transpose()
print(arr1)
print("transposed array:",arr1.T)

[[1 2 3]
 [6 7 8]]
transposed array: [[1 6]
 [2 7]
 [3 8]]

In [122]:
# Expand dimensions:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [124]:
y = np.expand_dims(x, axis=0) # Add row dimension

In [129]:
y.shape

(1, 3)

In [131]:
y = np.expand_dims(x, axis=1)
y

array([[1],
       [2],
       [3]])

In [132]:
y.shape

(3, 1)

In [133]:
x = np.array([[[1,2,3]]])

In [134]:
x

array([[[1, 2, 3]]])

In [137]:
x.shape

(1, 1, 3)

In [140]:
#Removes dimensions of size 1.
y = np.squeeze(x)
y

array([1, 2, 3])

In [141]:
y.shape

(3,)

In [142]:
# Mathematical expression:

In [169]:
x = np.array([1,2,3,-4])
x

array([ 1,  2,  3, -4])

In [145]:
x+5

array([6, 7, 8, 9])

In [150]:
x*2

array([2, 4, 6, 8])

In [155]:
y = np.array([1,1,0,1])

In [156]:
x + y

array([2, 3, 3, 5])

In [157]:
x*y

array([1, 2, 0, 4])

In [159]:
np.power(x,2)

array([ 1,  4,  9, 16])

In [163]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [164]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [165]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [166]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [167]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [170]:
np.abs(x)

array([1, 2, 3, 4])