In [10]:
import pandas as pd

In [25]:
# create dataframe
sample_data = pd.DataFrame([1,2,3,4], columns=["ink_count"])
sample_data

   ink_count
0          1
1          2
2          3
3          4

In [26]:
sample_data.reset_index(drop=True)

   ink_count
0          1
1          2
2          3
3          4

In [35]:
# Load data
data = pd.read_csv("/Users/raviranjan/Documents/personal/ai_crash_course/data/housing_price_data_set.csv")

In [36]:
data = data.drop(columns = ["Unnamed: 0"])
data

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [37]:
#check head
data.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [38]:
#check tail
data.tail()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [40]:
#check shape
data.shape

(546, 12)

In [44]:
#check columns
data.columns

Index(['price', 'lotsize', 'bedrooms', 'bathrms', 'stories', 'driveway',
       'recroom', 'fullbase', 'gashw', 'airco', 'garagepl', 'prefarea'],
      dtype='object')

In [45]:
len(data.columns)

12

In [50]:
#check datatypes
data.dtypes

price       float64
lotsize       int64
bedrooms      int64
bathrms       int64
stories       int64
driveway     object
recroom      object
fullbase     object
gashw        object
airco        object
garagepl      int64
prefarea     object
dtype: object

In [ ]:
data.

In [51]:
# check info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     546 non-null    float64
 1   lotsize   546 non-null    int64
 2   bedrooms  546 non-null    int64
 3   bathrms   546 non-null    int64
 4   stories   546 non-null    int64
 5   driveway  546 non-null    object
 6   recroom   546 non-null    object
 7   fullbase  546 non-null    object
 8   gashw     546 non-null    object
 9   airco     546 non-null    object
 10  garagepl  546 non-null    int64
 11  prefarea  546 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 51.3+ KB

In [52]:
# df.describe()
data.describe()

,price,lotsize,bedrooms,bathrms,stories,garagepl
count,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000
mean,68121.597070,5150.265568,2.965201,1.285714,1.807692,0.692308
std,26702.670926,2168.158725,0.737388,0.502158,0.868203,0.861307
min,25000.000000,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,49125.000000,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,62000.000000,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,82000.000000,6360.000000,3.000000,2.000000,2.000000,1.000000
max,190000.000000,16200.000000,6.000000,4.000000,4.000000,3.000000

In [61]:
# Select 1 columns
data["driveway"]

0      yes
1      yes
2      yes
3      yes
4      yes
      ...
541    yes
542    yes
543    yes
544    yes
545    yes
Name: driveway, Length: 546, dtype: object

In [60]:
# Selct multiple columns
data[["driveway", "recroom"]]

    driveway recroom
0        yes      no
1        yes      no
2        yes      no
3        yes     yes
4        yes      no
..       ...     ...
541      yes     yes
542      yes      no
543      yes     yes
544      yes     yes
545      yes      no

[546 rows x 2 columns]

In [71]:
# Select by integer position
data.iloc[1:4]

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no

# select by label
data.loc[5, "driveway"]

In [75]:
#filter rows
data[data["bedrooms"]>4]

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
43,92000.0,8580,5,3,2,yes,no,no,no,no,2,no
50,55000.0,5300,5,2,2,yes,no,no,no,no,0,no
119,116000.0,6840,5,1,2,yes,yes,yes,no,yes,1,no
148,80000.0,4800,5,2,3,no,no,yes,yes,no,0,no
158,62000.0,1905,5,1,2,no,no,yes,no,no,0,no
184,28000.0,3420,5,1,2,no,no,no,no,no,0,no
201,53900.0,2520,5,2,1,no,no,yes,no,yes,1,no
237,50000.0,3600,6,1,2,yes,no,no,no,no,1,no
354,86900.0,4300,6,2,2,yes,no,no,no,no,0,no
367,120000.0,7950,5,2,2,yes,no,yes,yes,no,2,no
368,145000.0,16200,5,3,2,yes,no,no,no,no,0,no
456,79500.0,5400,5,1,2,yes,yes,yes,no,yes,0,yes

In [82]:
# Filter using AND
data[(data.bedrooms>4) & (data.prefarea=='yes')]

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
456,79500.0,5400,5,1,2,yes,yes,yes,no,yes,0,yes

In [85]:
# Filter using OR
data[(data.bedrooms>4) | (data.prefarea=='yes')]

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
43,92000.0,8580,5,3,2,yes,no,no,no,no,2,no
50,55000.0,5300,5,2,2,yes,no,no,no,no,0,no
119,116000.0,6840,5,1,2,yes,yes,yes,no,yes,1,no
148,80000.0,4800,5,2,3,no,no,yes,yes,no,0,no
158,62000.0,1905,5,1,2,no,no,yes,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
481,95000.0,5700,3,1,1,yes,yes,yes,no,yes,2,yes
482,95500.0,6600,2,2,4,yes,no,yes,no,no,0,yes
483,51500.0,4000,2,1,1,yes,no,no,no,no,0,yes
484,62900.0,4880,3,1,1,yes,no,no,no,no,2,yes
485,118500.0,4880,4,2,2,yes,no,no,no,yes,1,yes

In [89]:
# Negate condition
data[~(data.prefarea=='yes')]

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [101]:
# Cleaner filtering
data.query("bedrooms==4")

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
17,40750.0,5200,4,1,3,yes,no,no,no,no,0,no
21,65900.0,4510,4,2,2,yes,no,yes,no,no,0,no
31,48000.0,3500,4,1,2,yes,no,no,no,yes,2,no
38,82000.0,5400,4,2,2,yes,no,no,no,yes,2,no
42,82000.0,4640,4,1,2,yes,no,no,no,no,1,no
...,...,...,...,...,...,...,...,...,...,...,...,...
521,105000.0,6000,4,2,4,yes,yes,no,no,yes,1,no
522,108000.0,6000,4,2,4,yes,no,no,no,yes,1,no
523,110000.0,6000,4,2,4,yes,no,no,no,no,2,no
524,113000.0,6000,4,2,4,yes,no,no,no,yes,1,no
539,85000.0,7320,4,2,2,yes,no,no,no,no,0,no

In [102]:
# unique()
data.recroom.unique()

array(['no', 'yes'], dtype=object)

In [103]:
# nunique() count values
data.recroom.nunique()

2

In [104]:
# Frequency of each value
data["bedrooms"].value_counts()

bedrooms
3    301
2    136
4     95
5     10
1      2
6      2
Name: count, dtype: int64

In [105]:
#find missing values
data.isna()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
541,False,False,False,False,False,False,False,False,False,False,False,False
542,False,False,False,False,False,False,False,False,False,False,False,False
543,False,False,False,False,False,False,False,False,False,False,False,False
544,False,False,False,False,False,False,False,False,False,False,False,False
545,False,False,False,False,False,False,False,False,False,False,False,False

In [108]:
# count missing values
data.isna().sum()

price       0
lotsize     0
bedrooms    0
bathrms     0
stories     0
driveway    0
recroom     0
fullbase    0
gashw       0
airco       0
garagepl    0
prefarea    0
dtype: int64

In [109]:
# Non- missing values
data.notna()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
541,True,True,True,True,True,True,True,True,True,True,True,True
542,True,True,True,True,True,True,True,True,True,True,True,True
543,True,True,True,True,True,True,True,True,True,True,True,True
544,True,True,True,True,True,True,True,True,True,True,True,True
545,True,True,True,True,True,True,True,True,True,True,True,True

In [110]:
# Remove row with missing values
data.dropna()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [111]:
# Remove row with specific columns
data.dropna(subset=["prefarea"])

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [141]:
data["member_allowed"] = None

In [142]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price           546 non-null    float64
 1   lotsize         546 non-null    int64
 2   bedrooms        546 non-null    int64
 3   bathrms         546 non-null    int64
 4   stories         546 non-null    int64
 5   driveway        546 non-null    object
 6   recroom         546 non-null    object
 7   fullbase        546 non-null    object
 8   gashw           546 non-null    object
 9   airco           546 non-null    object
 10  garagepl        546 non-null    int64
 11  prefarea        546 non-null    object
 12  member_allowed  0 non-null      object
dtypes: float64(1), int64(5), object(7)
memory usage: 55.6+ KB

In [127]:
# Fill missing values
data["member_allowed"]= data["member_allowed"].fillna(5)?

/var/folders/17/35md0zr16hvdjvkw_fln7jxw0000gn/T/ipykernel_63474/2752606058.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["member_allowed"]= data["member_allowed"].fillna(5)

In [ ]:
# Impute with mean
data["member_allowed"].fillna(data["bedrooms"].mean())

In [136]:
# Impute with median
data["member_allowed"].fillna(data["bedrooms"].median())

/var/folders/17/35md0zr16hvdjvkw_fln7jxw0000gn/T/ipykernel_63474/3089189853.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["member_allowed"].fillna(data["bedrooms"].median())

0      3.0
1      3.0
2      3.0
3      3.0
4      3.0
      ...
541    3.0
542    3.0
543    3.0
544    3.0
545    3.0
Name: member_allowed, Length: 546, dtype: float64

In [143]:
# Remove duplicate rows
data.drop_duplicates()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea,member_allowed
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no,None
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no,None
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no,None
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no,None
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no,None
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no,None
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no,None
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no,None
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no,None

In [146]:
# Remove duplicate columns
data.drop_duplicates("member_allowed")

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea,member_allowed
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no,5

In [147]:
data

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea,member_allowed
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no,5
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no,5
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no,5
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no,5
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no,5
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no,5
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no,5
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no,5
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no,5

In [148]:
#Sort asscending
data.sort_values("bedrooms")

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea,member_allowed
18,45000.0,3450,1,1,1,yes,no,no,no,no,0,no,5
233,32500.0,3970,1,1,1,no,no,no,no,no,0,no,5
105,43000.0,4600,2,1,1,yes,no,no,no,no,0,no,5
106,48000.0,3720,2,1,1,no,no,no,no,yes,0,no,5
245,37200.0,2910,2,1,1,no,no,no,no,no,0,no,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,116000.0,6840,5,1,2,yes,yes,yes,no,yes,1,no,5
50,55000.0,5300,5,2,2,yes,no,no,no,no,0,no,5
158,62000.0,1905,5,1,2,no,no,yes,no,no,0,no,5
354,86900.0,4300,6,2,2,yes,no,no,no,no,0,no,5
237,50000.0,3600,6,1,2,yes,no,no,no,no,1,no,5

In [149]:
#Sort descending
data.sort_values("bedrooms", ascending=False)

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea,member_allowed
237,50000.0,3600,6,1,2,yes,no,no,no,no,1,no,5
354,86900.0,4300,6,2,2,yes,no,no,no,no,0,no,5
148,80000.0,4800,5,2,3,no,no,yes,yes,no,0,no,5
456,79500.0,5400,5,1,2,yes,yes,yes,no,yes,0,yes,5
50,55000.0,5300,5,2,2,yes,no,no,no,no,0,no,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,72500.0,5720,2,1,2,yes,no,no,no,yes,0,yes,5
98,35000.0,3500,2,1,1,yes,yes,no,no,no,0,no,5
234,36000.0,3000,2,1,2,yes,no,no,no,no,0,no,5
233,32500.0,3970,1,1,1,no,no,no,no,no,0,no,5
18,45000.0,3450,1,1,1,yes,no,no,no,no,0,no,5

In [150]:
# Sort by multi-columns
data.sort_values(["bedrooms", "price"])

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea,member_allowed
233,32500.0,3970,1,1,1,no,no,no,no,no,0,no,5
18,45000.0,3450,1,1,1,yes,no,no,no,no,0,no,5
55,25000.0,3620,2,1,1,yes,no,no,no,no,0,no,5
238,26000.0,3000,2,1,1,yes,no,yes,no,no,2,no,5
138,26500.0,2990,2,1,1,no,no,no,no,no,1,no,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,116000.0,6840,5,1,2,yes,yes,yes,no,yes,1,no,5
367,120000.0,7950,5,2,2,yes,no,yes,yes,no,2,no,5
368,145000.0,16200,5,3,2,yes,no,no,no,no,0,no,5
237,50000.0,3600,6,1,2,yes,no,no,no,no,1,no,5
354,86900.0,4300,6,2,2,yes,no,no,no,no,0,no,5

In [166]:
# Rename a column
data.rename(columns ={"member_allowed":"members_count"}, inplace=True)

In [167]:
#Remove a column
data.drop(columns =["members_count"])

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [169]:
# Apply a function
data["members_count"] = data["bedrooms"].apply(lambda x: x+1)

In [171]:
# Map individual values
data["prefarea"].map({"yes":1, "no":0})

0      0
1      0
2      0
3      0
4      0
      ..
541    0
542    0
543    0
544    0
545    0
Name: prefarea, Length: 546, dtype: int64

In [173]:
#Replace values
data["prefarea"].replace({"yes":1, "no":0})

/var/folders/17/35md0zr16hvdjvkw_fln7jxw0000gn/T/ipykernel_63474/3809758391.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["prefarea"].replace({"yes":1, "no":0})

0      0
1      0
2      0
3      0
4      0
      ..
541    0
542    0
543    0
544    0
545    0
Name: prefarea, Length: 546, dtype: int64

In [174]:
# Change data types
data["bedrooms"].astype("float")

0      3.0
1      2.0
2      3.0
3      3.0
4      2.0
      ...
541    3.0
542    3.0
543    3.0
544    3.0
545    3.0
Name: bedrooms, Length: 546, dtype: float64

In [178]:
# Aggregate by groups
data.groupby("prefarea")["price"].count()

prefarea
no     418
yes    128
Name: price, dtype: int64

In [177]:
#sum by groups
data.groupby("prefarea")["price"].sum()

prefarea
no     26444137.0
yes    10750255.0
Name: price, dtype: float64

In [179]:
#Mean by groups
data.groupby("prefarea")["price"].mean()

prefarea
no     63263.485646
yes    83986.367188
Name: price, dtype: float64

In [181]:
#Count by records by group
data.groupby("prefarea")["price"].count()

prefarea
no     418
yes    128
Name: price, dtype: int64

In [185]:
#Multiple Aggregtion
aggregated_data = data.groupby("prefarea")["price"].agg(["mean", "max", "min", "count"])

In [187]:
aggregated_data.reset_index()

  prefarea          mean       max      min  count
0       no  63263.485646  175000.0  25000.0    418
1      yes  83986.367188  190000.0  31900.0    128

In [190]:
# Number of rows per group
data["prefarea"].size

546

| Pandas formula                         | Example                                                     | When to use                          |
| -------------------------------------- | ----------------------------------------------------------- | ------------------------------------ |
| `pd.DataFrame()`                       | `pd.DataFrame({"A":[1,2]})`                                 | Create a DataFrame                   |
| `df.head(n)`                           | `df.head(5)`                                                | View first rows                      |
| `df.tail(n)`                           | `df.tail(5)`                                                | View last rows                       |
| `df.shape`                             | `df.shape` → `(100, 5)`                                     | Get rows and columns                 |
| `df.columns`                           | `df.columns`                                                | Get column names                     |
| `df.dtypes`                            | `df.dtypes`                                                 | Check data types                     |
| `df.info()`                            | `df.info()`                                                 | Inspect columns, types, nulls        |
| `df.describe()`                        | `df.describe()`                                             | Summary statistics                   |
| `df["col"]`                            | `df["age"]`                                                 | Select one column                    |
| `df[["c1","c2"]]`                      | `df[["age","salary"]]`                                      | Select multiple columns              |
| `df.iloc[]`                            | `df.iloc[0, 2]`                                             | Select by integer position           |
| `df.loc[]`                             | `df.loc[5, "salary"]`                                       | Select by label                      |
| `df[df["age"] > 30]`                   | `df[df["age"] > 30]`                                        | Filter rows                          |
| `df[(c1) & (c2)]`                      | `df[(df.age>30) & (df.salary>50000)]`                       | Filter using AND                     |
| `df[(c1) \| (c2)]`                     | `df[(df.age<20) \| (df.age>60)]`                            | Filter using OR                      |
| `~condition`                           | `df[~(df["city"]=="Delhi")]`                                | Negate a condition                   |
| `df.query()`                           | `df.query("age > 30")`                                      | Cleaner filtering                    |
| `df["col"].unique()`                   | `df["city"].unique()`                                       | Find unique values                   |
| `df["col"].nunique()`                  | `df["user_id"].nunique()`                                   | Count unique values                  |
| `df["col"].value_counts()`             | `df["city"].value_counts()`                                 | Frequency of each value              |
| `df.isna()`                            | `df.isna()`                                                 | Find missing values                  |
| `df.isna().sum()`                      | `df.isna().sum()`                                           | Count missing values                 |
| `df.notna()`                           | `df["age"].notna()`                                         | Find non-missing values              |
| `df.dropna()`                          | `df.dropna()`                                               | Remove rows with missing values      |
| `df.dropna(subset=[])`                 | `df.dropna(subset=["age"])`                                 | Remove rows missing specific columns |
| `df.fillna()`                          | `df["age"].fillna(30)`                                      | Fill missing values                  |
| `df["col"].fillna(df["col"].mean())`   | `df["age"].fillna(df["age"].mean())`                        | Impute with mean                     |
| `df["col"].fillna(df["col"].median())` | `df["age"].fillna(df["age"].median())`                      | Impute with median                   |
| `df.drop_duplicates()`                 | `df.drop_duplicates()`                                      | Remove duplicate rows                |
| `df.drop_duplicates("col")`            | `df.drop_duplicates("user_id")`                             | Remove duplicates based on column    |
| `df.sort_values()`                     | `df.sort_values("salary")`                                  | Sort ascending                       |
| `df.sort_values(..., ascending=False)` | `df.sort_values("salary", ascending=False)`                 | Sort descending                      |
| `df.sort_values(["c1","c2"])`          | `df.sort_values(["dept","salary"])`                         | Sort by multiple columns             |
| `df["new"] = ...`                      | `df["annual"] = df["monthly"]*12`                           | Create a column                      |
| `df.rename()`                          | `df.rename(columns={"old":"new"})`                          | Rename columns                       |
| `df.drop(columns=[])`                  | `df.drop(columns=["age"])`                                  | Remove columns                       |
| `df["col"].apply()`                    | `df["age"].apply(lambda x:x+1)`                             | Apply a function                     |
| `df["col"].map()`                      | `df["gender"].map({"M":1,"F":0})`                           | Map individual values                |
| `df.replace()`                         | `df["gender"].replace({"M":1,"F":0})`                       | Replace values                       |
| `df.astype()`                          | `df["age"].astype(int)`                                     | Change data type                     |
| `df.groupby()`                         | `df.groupby("city")["salary"].mean()`                       | Aggregate by groups                  |
| `df.groupby().sum()`                   | `df.groupby("dept")["sales"].sum()`                         | Sum by group                         |
| `df.groupby().mean()`                  | `df.groupby("dept")["salary"].mean()`                       | Mean by group                        |
| `df.groupby().count()`                 | `df.groupby("dept")["id"].count()`                          | Count records per group              |
| `df.groupby().agg()`                   | `df.groupby("dept")["salary"].agg(["mean","max","min"])`    | Multiple aggregations                |
| `df.groupby().size()`                  | `df.groupby("dept").size()`                                 | Number of rows per group             |
| `df["col"].sum()`                      | `df["revenue"].sum()`                                       | Total                                |
| `df["col"].mean()`                     | `df["salary"].mean()`                                       | Average                              |
| `df["col"].median()`                   | `df["salary"].median()`                                     | Median                               |
| `df["col"].std()`                      | `df["salary"].std()`                                        | Standard deviation                   |
| `df["col"].min()`                      | `df["salary"].min()`                                        | Minimum                              |
| `df["col"].max()`                      | `df["salary"].max()`                                        | Maximum                              |
| `df["col"].quantile()`                 | `df["salary"].quantile(.95)`                                | Percentile                           |
| `df.corr()`                            | `df[["age","salary"]].corr()`                               | Correlation                          |
| `df["col"].rank()`                     | `df["salary"].rank(ascending=False)`                        | Rank values                          |
| `pd.merge()`                           | `pd.merge(df1,df2,on="user_id")`                            | Join two DataFrames                  |
| `pd.merge(..., how="left")`            | `pd.merge(df1,df2,on="id",how="left")`                      | Left join                            |
| `pd.merge(..., how="inner")`           | `pd.merge(df1,df2,on="id",how="inner")`                     | Inner join                           |
| `pd.concat()`                          | `pd.concat([df1,df2])`                                      | Combine DataFrames                   |
| `pd.concat(..., axis=1)`               | `pd.concat([df1,df2],axis=1)`                               | Combine columns                      |
| `df.pivot_table()`                     | `df.pivot_table(values="sales",index="city",aggfunc="sum")` | Reshape + aggregate                  |
| `df["col"].str.lower()`                | `df["name"].str.lower()`                                    | Convert strings to lowercase         |
| `df["col"].str.upper()`                | `df["name"].str.upper()`                                    | Convert strings to uppercase         |
| `df["col"].str.contains()`             | `df[df["name"].str.contains("raj")]`                        | Search within strings                |
| `df["col"].str.startswith()`           | `df[df["name"].str.startswith("A")]`                        | Filter by prefix                     |
| `df["col"].str.split()`                | `df["name"].str.split(" ")`                                 | Split strings                        |
| `pd.to_datetime()`                     | `df["date"]=pd.to_datetime(df["date"])`                     | Convert to datetime                  |
| `df["date"].dt.year`                   | `df["date"].dt.year`                                        | Extract year                         |
| `df["date"].dt.month`                  | `df["date"].dt.month`                                       | Extract month                        |
| `df["date"].dt.day`                    | `df["date"].dt.day`                                         | Extract day                          |
| `df["date"].dt.dayofweek`              | `df["date"].dt.dayofweek`                                   | Get weekday                          |
| `df.shift()`                           | `df["sales"].shift(1)`                                      | Previous/next row comparison         |
| `df.diff()`                            | `df["sales"].diff()`                                        | Difference between rows              |
| `df.cumsum()`                          | `df["sales"].cumsum()`                                      | Cumulative sum                       |
| `df.pct_change()`                      | `df["sales"].pct_change()`                                  | Percentage change                    |
| `df.reset_index()`                     | `df.reset_index(drop=True)`                                 | Reset index                          |
| `df.set_index()`                       | `df.set_index("user_id")`                                   | Set a column as index                |
| `df.sample()`                          | `df.sample(100)`                                            | Randomly sample rows                 |
| `df.nlargest()`                        | `df.nlargest(5,"salary")`                                   | Top N rows                           |
| `df.nsmallest()`                       | `df.nsmallest(5,"salary")`                                  | Bottom N rows                        |

In [191]:
# Sum Total
data["price"].sum()

np.float64(37194392.0)

In [ ]:
# Averagge

In [ ]:
# Median

In [ ]:
# Maximum

In [ ]:
#Minimum

In [ ]:
# Percentile

In [ ]:
# Standard Deviation

In [ ]:
# Correlation

In [ ]:
# Rank values

In [ ]:
# Join to df

In [ ]:
#Left Join

In [ ]:
# Inner Join

In [ ]:
# Combines Dataframe

In [ ]:
# Combine column

In [ ]:
# Reshape + Aggregate

In [ ]:
# Convert string to lowercase

In [ ]:
# Convert string to uppercase

In [ ]:
# Search within strings

In [ ]:
# Filter by prefix

In [ ]:
# Split string

In [ ]:
# Conver to datetime

In [ ]:
# Extract year

In [ ]:
# Extract Month

In [ ]:
# Extract day

In [ ]:
# Extract wekday

In [ ]:
# Previous/next row comparision

In [ ]:
# Difference between rows

In [ ]:
# Cummulative Sum

In [ ]:
# Percentage change

In [ ]:
#Reset Index

In [ ]:
#Set a column as index

In [ ]:
#Randomly Sample rows

In [ ]:
# Top N rows

In [ ]:
# Bottom N rows